use crate::palette::{render_template, Palette};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ApplyMode {
    Live,
    Restart,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct AdapterStatus {
    pub name: String,
    pub apply_mode: ApplyMode,
    pub success: bool,
    pub paths: Vec<String>,
    pub note: Option<String>,
    pub error: Option<String>,
}

#[derive(Debug)]
pub struct ApplyContext {
    pub home_dir: PathBuf,
    pub config_dir: PathBuf,
    pub data_dir: PathBuf,
    pub gtk_base_theme_name: String,
    pub gtk3_base_css: String,
    pub gtk4_base_css: String,
}

impl ApplyContext {
    pub fn from_env() -> Result<Self> {
        let home_dir = std::env::var_os("HOME")
            .map(PathBuf::from)
            .context("HOME is not set")?;

        let config_dir = std::env::var_os("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| home_dir.join(".config"));
        let data_dir = std::env::var_os("XDG_DATA_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| home_dir.join(".local/share"));

        Ok(Self {
            home_dir,
            config_dir,
            data_dir,
            gtk_base_theme_name: std::env::var("WALBRIDGE_GTK_BASE_THEME_NAME")
                .unwrap_or_else(|_| "adw-gtk3-dark".into()),
            gtk3_base_css: std::env::var("WALBRIDGE_GTK3_BASE_CSS").unwrap_or_default(),
            gtk4_base_css: std::env::var("WALBRIDGE_GTK4_BASE_CSS").unwrap_or_default(),
        })
    }
}

pub fn apply_all(ctx: &ApplyContext, palette: &Palette) -> Vec<AdapterStatus> {
    let adapters = [
        (
            "gtk",
            apply_gtk as fn(&ApplyContext, &Palette) -> Result<AdapterStatus>,
        ),
        ("qt", apply_qt),
        ("wezterm", apply_wezterm),
        ("starship", apply_starship),
        ("fish", apply_fish),
        ("atuin", apply_atuin),
        ("ghostty", apply_ghostty),
        ("bat", apply_bat),
        ("vscode", apply_vscode),
        ("btop", apply_btop),
    ];

    adapters
        .into_iter()
        .map(|(name, apply)| match apply(ctx, palette) {
            Ok(status) => status,
            Err(error) => AdapterStatus {
                name: name.to_string(),
                apply_mode: ApplyMode::Restart,
                success: false,
                paths: Vec::new(),
                note: None,
                error: Some(format!("{error:#}")),
            },
        })
        .collect()
}

fn apply_gtk(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    anyhow::ensure!(
        !ctx.gtk3_base_css.is_empty() && !ctx.gtk4_base_css.is_empty(),
        "missing walbridge GTK base theme paths"
    );
    let gtk4_rendered = render_gtk_theme(
        include_str!("../templates/gtk.css"),
        &ctx.gtk4_base_css,
        &palette.render_context(),
    );
    let gtk3_rendered = render_gtk_theme(
        include_str!("../templates/gtk3.css"),
        &ctx.gtk3_base_css,
        &palette.render_context(),
    );
    let current_theme = current_gtk_theme().ok();
    let next_theme_name = match current_theme.as_deref() {
        Some("WalbridgeA") => "WalbridgeB",
        _ => "WalbridgeA",
    };
    let theme_root = ctx.data_dir.join("themes").join(next_theme_name);
    let gtk3_theme = theme_root.join("gtk-3.0/gtk.css");
    let gtk4_theme = theme_root.join("gtk-4.0/gtk.css");
    let theme_index = theme_root.join("index.theme");
    let gtk3_override = ctx.config_dir.join("gtk-3.0/gtk.css");
    let gtk4_override = ctx.config_dir.join("gtk-4.0/gtk.css");

    write_text(&gtk3_theme, &gtk3_rendered)?;
    write_text(&gtk4_theme, &gtk4_rendered)?;
    write_text(
        &theme_index,
        &format!(
            "[Desktop Entry]\nType=X-GNOME-Metatheme\nName={next_theme_name}\nComment=Generated by walbridge\n\n[X-GNOME-Metatheme]\nGtkTheme={next_theme_name}\nMetacityTheme={base}\nIconTheme=Papirus\nCursorTheme=catppuccin-mocha-lavender-cursors\nButtonLayout=menu:minimize,maximize,close\n",
            base = ctx.gtk_base_theme_name,
        ),
    )?;
    clear_override_css(&gtk3_override)?;
    clear_override_css(&gtk4_override)?;
    set_gtk_theme(next_theme_name)?;

    Ok(AdapterStatus {
        name: "gtk".into(),
        apply_mode: ApplyMode::Live,
        success: true,
        paths: vec![
            gtk3_theme.display().to_string(),
            gtk4_theme.display().to_string(),
            theme_index.display().to_string(),
            gtk3_override.display().to_string(),
            gtk4_override.display().to_string(),
        ],
        note: Some(
            "Generated alternating GTK themes layered on a real base theme and switched `gtk-theme-name` live. Apps that had the old walbridge `gtk.css` override loaded may need one restart to migrate."
                .into(),
        ),
        error: None,
    })
}

fn apply_qt(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let qt5_config = ctx.config_dir.join("qt5ct/qt5ct.conf");
    let qt6_config = ctx.config_dir.join("qt6ct/qt6ct.conf");
    let qt5_colors = ctx.config_dir.join("qt5ct/colors/walbridge.conf");
    let qt6_colors = ctx.config_dir.join("qt6ct/colors/walbridge.conf");

    let existing_qt5 = fs::read_to_string(&qt5_config).unwrap_or_default();
    let existing_qt6 = fs::read_to_string(&qt6_config).unwrap_or_default();

    let qt5_style = preferred_qt_style(&existing_qt5);
    let qt6_style = preferred_qt_style(&existing_qt6);
    let qt5_fonts = extract_qt_fonts(&existing_qt5);
    let qt6_fonts = extract_qt_fonts(&existing_qt6);

    write_text(&qt5_colors, &render_qt_colors(palette))?;
    write_text(&qt6_colors, &render_qt_colors(palette))?;
    write_text(
        &qt5_config,
        &render_qtct_config(
            &qt5_colors,
            &qt5_style,
            &qt5_fonts.general,
            &qt5_fonts.fixed,
        ),
    )?;
    write_text(
        &qt6_config,
        &render_qtct_config(
            &qt6_colors,
            &qt6_style,
            &qt6_fonts.general,
            &qt6_fonts.fixed,
        ),
    )?;

    Ok(AdapterStatus {
        name: "qt".into(),
        apply_mode: ApplyMode::Restart,
        success: true,
        paths: vec![
            qt5_config.display().to_string(),
            qt6_config.display().to_string(),
            qt5_colors.display().to_string(),
            qt6_colors.display().to_string(),
        ],
        note: Some("Qt apps usually need reopening to pick up qtct palette changes.".into()),
        error: None,
    })
}

fn apply_vscode(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let theme_json = render_template(
        include_str!("../templates/vscode-theme.json"),
        &palette.render_context(),
    );

    let extension_package = r#"{
  "name": "walbridge-pywal-theme",
  "displayName": "Walbridge Pywal Theme",
  "publisher": "walbridge",
  "version": "0.1.0",
  "engines": {
    "vscode": "^1.80.0"
  },
  "categories": [
    "Themes"
  ],
  "contributes": {
    "themes": [
      {
        "label": "Walbridge",
        "uiTheme": "vs-dark",
        "path": "./themes/walbridge-color-theme.json"
      }
    ]
  }
}
"#;

    let roots = [
        ctx.home_dir
            .join(".vscode-oss/extensions/walbridge.theme-pywal"),
        ctx.home_dir
            .join(".vscode/extensions/walbridge.theme-pywal"),
    ];

    let mut paths = Vec::new();
    for root in roots {
        let package_json = root.join("package.json");
        let theme_path = root.join("themes/walbridge-color-theme.json");
        write_text(&package_json, extension_package)?;
        write_text(&theme_path, &theme_json)?;
        paths.push(package_json.display().to_string());
        paths.push(theme_path.display().to_string());
    }

    Ok(AdapterStatus {
        name: "vscode".into(),
        apply_mode: ApplyMode::Restart,
        success: true,
        paths,
        note: Some("VS Code and VSCodium need reopening to pick up updated theme files.".into()),
        error: None,
    })
}

fn apply_btop(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let theme = render_template(
        include_str!("../templates/btop.theme"),
        &palette.render_context(),
    );
    let theme_path = ctx.config_dir.join("btop/themes/walbridge.theme");
    write_text(&theme_path, &theme)?;

    Ok(AdapterStatus {
        name: "btop".into(),
        apply_mode: ApplyMode::Restart,
        success: true,
        paths: vec![theme_path.display().to_string()],
        note: Some("Configure btop to use the `walbridge` theme, then reload it.".into()),
        error: None,
    })
}

fn apply_wezterm(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let theme_path = ctx.config_dir.join("wezterm/walbridge.lua");
    write_text(&theme_path, &render_wezterm_theme(palette))?;

    Ok(AdapterStatus {
        name: "wezterm".into(),
        apply_mode: ApplyMode::Live,
        success: true,
        paths: vec![theme_path.display().to_string()],
        note: Some(
            "Generated a runtime WezTerm config fragment named `walbridge`. Open WezTerm windows should reload when the config directory changes."
                .into(),
        ),
        error: None,
    })
}

fn apply_starship(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let template_path = ctx.config_dir.join("starship.toml");
    let target_path = ctx.config_dir.join("starship-walbridge.toml");
    let template = fs::read_to_string(&template_path).with_context(|| {
        format!(
            "failed to read starship template `{}`",
            template_path.display()
        )
    })?;
    let rendered = render_starship_config(&template, palette);
    write_text(&target_path, &rendered)?;

    Ok(AdapterStatus {
        name: "starship".into(),
        apply_mode: ApplyMode::Live,
        success: true,
        paths: vec![target_path.display().to_string()],
        note: Some(
            "Generated `starship-walbridge.toml` from the static Starship template. New prompts use it immediately."
                .into(),
        ),
        error: None,
    })
}

fn apply_fish(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let theme_path = ctx.config_dir.join("fish/conf.d/walbridge.fish");
    write_text(&theme_path, &render_fish_theme(palette))?;

    Ok(AdapterStatus {
        name: "fish".into(),
        apply_mode: ApplyMode::Restart,
        success: true,
        paths: vec![theme_path.display().to_string()],
        note: Some(
            "Generated a Fish theme snippet. New Fish shells will source it automatically.".into(),
        ),
        error: None,
    })
}

fn apply_atuin(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let theme_path = ctx.config_dir.join("atuin/themes/walbridge.toml");

    write_text(
        &theme_path,
        &render_template(
            include_str!("../templates/atuin-theme.toml"),
            &palette.render_context(),
        ),
    )?;

    Ok(AdapterStatus {
        name: "atuin".into(),
        apply_mode: ApplyMode::Restart,
        success: true,
        paths: vec![theme_path.display().to_string()],
        note: Some("Generated a walbridge Atuin theme. Atuin will use it once configured with `theme.name = \"walbridge\"`."
            .into()),
        error: None,
    })
}

fn apply_bat(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let theme = render_template(
        include_str!("../templates/bat.tmTheme"),
        &palette.render_context(),
    );
    let theme_path = ctx.config_dir.join("bat/themes/walbridge.tmTheme");
    write_text(&theme_path, &theme)?;

    let status = Command::new("bat")
        .args(["cache", "--build"])
        .status()
        .context("failed to run `bat cache --build`")?;
    anyhow::ensure!(status.success(), "`bat cache --build` exited with {status}");

    Ok(AdapterStatus {
        name: "bat".into(),
        apply_mode: ApplyMode::Live,
        success: true,
        paths: vec![theme_path.display().to_string()],
        note: Some(
            "Generated the runtime bat theme `walbridge` and rebuilt bat's theme cache. New bat invocations will use it immediately."
                .into(),
        ),
        error: None,
    })
}

fn apply_ghostty(ctx: &ApplyContext, palette: &Palette) -> Result<AdapterStatus> {
    let theme = render_ghostty_theme(palette);
    let theme_path = ctx.config_dir.join("ghostty/themes/walbridge");
    write_text(&theme_path, &theme)?;

    Ok(AdapterStatus {
        name: "ghostty".into(),
        apply_mode: ApplyMode::Restart,
        success: true,
        paths: vec![theme_path.display().to_string()],
        note: Some(
            "Generated a runtime Ghostty theme named `walbridge`. Restart Ghostty or reload its config to pick up palette changes."
                .into(),
        ),
        error: None,
    })
}

fn render_qt_colors(palette: &Palette) -> String {
    let base00 = palette.color("base00");
    let base01 = palette.color("base01");
    let base02 = palette.color("base02");
    let base03 = palette.color("base03");
    let base04 = palette.color("base04");
    let base05 = palette.color("base05");
    let base08 = palette.color("base08");
    let base0d = palette.color("base0D");
    let base0e = palette.color("base0E");

    let active = [
        base05.hashtag(),
        base01.hashtag(),
        base03.hashtag(),
        base02.hashtag(),
        base00.hashtag(),
        base01.hashtag(),
        base05.hashtag(),
        base00.hashtag(),
        base05.hashtag(),
        base00.hashtag(),
        base01.hashtag(),
        base00.hashtag(),
        base0d.hashtag(),
        base00.hashtag(),
        base0d.hashtag(),
        base0e.hashtag(),
        base01.hashtag(),
        base04.hashtag(),
        base01.hashtag(),
        base05.hashtag(),
        base05.with_alpha(0x80),
    ];

    let disabled = [
        base04.hashtag(),
        base01.hashtag(),
        base03.hashtag(),
        base02.hashtag(),
        base00.hashtag(),
        base01.hashtag(),
        base04.hashtag(),
        base00.hashtag(),
        base04.hashtag(),
        base00.hashtag(),
        base01.hashtag(),
        base00.hashtag(),
        base03.hashtag(),
        base00.hashtag(),
        base0d.hashtag(),
        base0e.hashtag(),
        base01.hashtag(),
        base04.hashtag(),
        base01.hashtag(),
        base04.hashtag(),
        base04.with_alpha(0x80),
    ];

    let inactive = [
        base05.hashtag(),
        base01.hashtag(),
        base03.hashtag(),
        base02.hashtag(),
        base00.hashtag(),
        base01.hashtag(),
        base05.hashtag(),
        base00.hashtag(),
        base05.hashtag(),
        base00.hashtag(),
        base01.hashtag(),
        base00.hashtag(),
        base0d.hashtag(),
        base00.hashtag(),
        base0d.hashtag(),
        base08.hashtag(),
        base01.hashtag(),
        base04.hashtag(),
        base01.hashtag(),
        base05.hashtag(),
        base05.with_alpha(0x80),
    ];

    format!(
        "[ColorScheme]\nactive_colors={}\ndisabled_colors={}\ninactive_colors={}\n",
        active.join(", "),
        disabled.join(", "),
        inactive.join(", "),
    )
}

fn render_wezterm_theme(palette: &Palette) -> String {
    let terminal = palette.terminal_palette();
    let base00 = palette.color("base00");
    let base01 = palette.color("base01");
    let base02 = palette.color("base02");
    let base03 = palette.color("base03");
    let base05 = palette.color("base05");
    let base07 = palette.color("base07");
    let base09 = palette.color("base09");

    format!(
        concat!(
            "return {{\n",
            "  color_scheme = \"walbridge\",\n",
            "  color_schemes = {{\n",
            "    walbridge = {{\n",
            "      ansi = {{ \"{ansi0}\", \"{ansi1}\", \"{ansi2}\", \"{ansi3}\", \"{ansi4}\", \"{ansi5}\", \"{ansi6}\", \"{ansi7}\" }},\n",
            "      brights = {{ \"{bright0}\", \"{bright1}\", \"{bright2}\", \"{bright3}\", \"{bright4}\", \"{bright5}\", \"{bright6}\", \"{bright7}\" }},\n",
            "      background = \"{base00}\",\n",
            "      cursor_bg = \"{base05}\",\n",
            "      cursor_fg = \"{base00}\",\n",
            "      compose_cursor = \"{base07}\",\n",
            "      foreground = \"{base05}\",\n",
            "      scrollbar_thumb = \"{base01}\",\n",
            "      selection_bg = \"{base03}\",\n",
            "      selection_fg = \"{base05}\",\n",
            "      split = \"{base03}\",\n",
            "      visual_bell = \"{base09}\",\n",
            "      tab_bar = {{\n",
            "        background = \"{base01}\",\n",
            "        inactive_tab_edge = \"{base01}\",\n",
            "        active_tab = {{ bg_color = \"{base02}\", fg_color = \"{base05}\" }},\n",
            "        inactive_tab = {{ bg_color = \"{base00}\", fg_color = \"{base04}\" }},\n",
            "        inactive_tab_hover = {{ bg_color = \"{base05}\", fg_color = \"{base00}\" }},\n",
            "        new_tab = {{ bg_color = \"{base01}\", fg_color = \"{base05}\" }},\n",
            "        new_tab_hover = {{ bg_color = \"{base05}\", fg_color = \"{base00}\" }},\n",
            "      }},\n",
            "    }},\n",
            "  }},\n",
            "  window_frame = {{\n",
            "    active_titlebar_bg = \"{base03}\",\n",
            "    active_titlebar_fg = \"{base05}\",\n",
            "    active_titlebar_border_bottom = \"{base03}\",\n",
            "    border_left_color = \"{base01}\",\n",
            "    border_right_color = \"{base01}\",\n",
            "    border_bottom_color = \"{base01}\",\n",
            "    border_top_color = \"{base01}\",\n",
            "    button_bg = \"{base01}\",\n",
            "    button_fg = \"{base05}\",\n",
            "    button_hover_bg = \"{base05}\",\n",
            "    button_hover_fg = \"{base03}\",\n",
            "    inactive_titlebar_bg = \"{base01}\",\n",
            "    inactive_titlebar_fg = \"{base05}\",\n",
            "    inactive_titlebar_border_bottom = \"{base03}\",\n",
            "  }},\n",
            "  colors = {{\n",
            "    tab_bar = {{\n",
            "      background = \"{base01}\",\n",
            "      inactive_tab_edge = \"{base01}\",\n",
            "      active_tab = {{ bg_color = \"{base02}\", fg_color = \"{base05}\" }},\n",
            "      inactive_tab = {{ bg_color = \"{base00}\", fg_color = \"{base04}\" }},\n",
            "      inactive_tab_hover = {{ bg_color = \"{base05}\", fg_color = \"{base00}\" }},\n",
            "      new_tab = {{ bg_color = \"{base01}\", fg_color = \"{base05}\" }},\n",
            "      new_tab_hover = {{ bg_color = \"{base05}\", fg_color = \"{base00}\" }},\n",
            "    }},\n",
            "  }},\n",
            "  command_palette_bg_color = \"{base01}\",\n",
            "  command_palette_fg_color = \"{base05}\",\n",
            "}}\n"
        ),
        base00 = base00.hashtag(),
        base01 = base01.hashtag(),
        base02 = base02.hashtag(),
        base03 = base03.hashtag(),
        base04 = palette.color("base04").hashtag(),
        base05 = base05.hashtag(),
        base07 = base07.hashtag(),
        base09 = base09.hashtag(),
        ansi0 = terminal.normal[0].hashtag(),
        ansi1 = terminal.normal[1].hashtag(),
        ansi2 = terminal.normal[2].hashtag(),
        ansi3 = terminal.normal[3].hashtag(),
        ansi4 = terminal.normal[4].hashtag(),
        ansi5 = terminal.normal[5].hashtag(),
        ansi6 = terminal.normal[6].hashtag(),
        ansi7 = terminal.normal[7].hashtag(),
        bright0 = terminal.bright[0].hashtag(),
        bright1 = terminal.bright[1].hashtag(),
        bright2 = terminal.bright[2].hashtag(),
        bright3 = terminal.bright[3].hashtag(),
        bright4 = terminal.bright[4].hashtag(),
        bright5 = terminal.bright[5].hashtag(),
        bright6 = terminal.bright[6].hashtag(),
        bright7 = terminal.bright[7].hashtag(),
    )
}

fn render_starship_config(template: &str, palette: &Palette) -> String {
    let terminal = palette.terminal_palette();
    let template = template.replace("palette = \"base16\"", "palette = \"walbridge\"");
    let mut result = String::new();
    let mut skipping_palette = false;

    for line in template.lines() {
        let trimmed = line.trim();
        if trimmed == "[palettes.base16]" {
            skipping_palette = true;
            continue;
        }

        if skipping_palette && trimmed.starts_with('[') && trimmed != "[palettes.base16]" {
            skipping_palette = false;
        }

        if !skipping_palette {
            result.push_str(line);
            result.push('\n');
        }
    }

    result.push('\n');
    result.push_str(&format!(
        concat!(
            "[palettes.walbridge]\n",
            "base00 = \"#{base00}\"\n",
            "base01 = \"#{base01}\"\n",
            "base02 = \"#{base02}\"\n",
            "base03 = \"#{base03}\"\n",
            "base04 = \"#{base04}\"\n",
            "base05 = \"#{base05}\"\n",
            "base06 = \"#{base06}\"\n",
            "base07 = \"#{base07}\"\n",
            "base08 = \"#{base08}\"\n",
            "base09 = \"#{base09}\"\n",
            "base0A = \"#{base0A}\"\n",
            "base0B = \"#{base0B}\"\n",
            "base0C = \"#{base0C}\"\n",
            "base0D = \"#{base0D}\"\n",
            "base0E = \"#{base0E}\"\n",
            "base0F = \"#{base0F}\"\n",
            "base10 = \"#{base00}\"\n",
            "base11 = \"#{base00}\"\n",
            "base12 = \"#{base08}\"\n",
            "base13 = \"#{base0A}\"\n",
            "base14 = \"#{base0B}\"\n",
            "base15 = \"#{base0C}\"\n",
            "base16 = \"#{base0D}\"\n",
            "base17 = \"#{base0E}\"\n",
            "black = \"#{black}\"\n",
            "blue = \"#{base0D}\"\n",
            "bright-black = \"#{bright_black}\"\n",
            "bright-blue = \"#{bright_blue}\"\n",
            "bright-cyan = \"#{bright_cyan}\"\n",
            "bright-green = \"#{bright_green}\"\n",
            "bright-magenta = \"#{bright_magenta}\"\n",
            "bright-purple = \"#{bright_magenta}\"\n",
            "bright-red = \"#{bright_red}\"\n",
            "bright-white = \"#{bright_white}\"\n",
            "bright-yellow = \"#{bright_yellow}\"\n",
            "brown = \"#{base0F}\"\n",
            "cyan = \"#{base0C}\"\n",
            "green = \"#{base0B}\"\n",
            "magenta = \"#{base0E}\"\n",
            "orange = \"#{base09}\"\n",
            "purple = \"#{base0E}\"\n",
            "red = \"#{base08}\"\n",
            "white = \"#{white}\"\n",
            "yellow = \"#{base0A}\"\n"
        ),
        base00 = palette.color("base00").hex(),
        base01 = palette.color("base01").hex(),
        base02 = palette.color("base02").hex(),
        base03 = palette.color("base03").hex(),
        base04 = palette.color("base04").hex(),
        base05 = palette.color("base05").hex(),
        base06 = palette.color("base06").hex(),
        base07 = palette.color("base07").hex(),
        base08 = palette.color("base08").hex(),
        base09 = palette.color("base09").hex(),
        base0A = palette.color("base0A").hex(),
        base0B = palette.color("base0B").hex(),
        base0C = palette.color("base0C").hex(),
        base0D = palette.color("base0D").hex(),
        base0E = palette.color("base0E").hex(),
        base0F = palette.color("base0F").hex(),
        black = terminal.normal[0].hex(),
        white = terminal.normal[7].hex(),
        bright_black = terminal.bright[0].hex(),
        bright_red = terminal.bright[1].hex(),
        bright_green = terminal.bright[2].hex(),
        bright_yellow = terminal.bright[3].hex(),
        bright_blue = terminal.bright[4].hex(),
        bright_magenta = terminal.bright[5].hex(),
        bright_cyan = terminal.bright[6].hex(),
        bright_white = terminal.bright[7].hex(),
    ));

    result
}

fn render_fish_theme(palette: &Palette) -> String {
    format!(
        concat!(
            "set -g fish_color_normal {base05}\n",
            "set -g fish_color_command {base0D}\n",
            "set -g fish_color_keyword {base0E}\n",
            "set -g fish_color_quote {base0B}\n",
            "set -g fish_color_redirection {base0C}\n",
            "set -g fish_color_end {base09}\n",
            "set -g fish_color_error {base08}\n",
            "set -g fish_color_param {base05}\n",
            "set -g fish_color_comment {base03}\n",
            "set -g fish_color_search_match --background={base01}\n",
            "set -g fish_color_selection --background={base02}\n",
            "set -g fish_color_operator {base0C}\n",
            "set -g fish_color_escape {base09}\n",
            "set -g fish_color_autosuggestion {base03}\n",
            "set -g fish_color_cancel {base08}\n",
            "set -g fish_color_cwd {base0B}\n",
            "set -g fish_color_cwd_root {base08}\n",
            "set -g fish_color_valid_path {base0C}\n",
            "set -g fish_color_option {base0A}\n",
            "set -g fish_color_history_current --bold\n",
            "set -g fish_color_host {base0D}\n",
            "set -g fish_color_host_remote {base0E}\n",
            "set -g fish_pager_color_prefix {base0C}\n",
            "set -g fish_pager_color_progress {base03}\n",
            "set -g fish_pager_color_completion {base05}\n",
            "set -g fish_pager_color_description {base04}\n",
            "set -g fish_pager_color_selected_background --background={base01}\n"
        ),
        base01 = palette.color("base01").hex(),
        base02 = palette.color("base02").hex(),
        base03 = palette.color("base03").hex(),
        base04 = palette.color("base04").hex(),
        base05 = palette.color("base05").hex(),
        base08 = palette.color("base08").hex(),
        base09 = palette.color("base09").hex(),
        base0A = palette.color("base0A").hex(),
        base0B = palette.color("base0B").hex(),
        base0C = palette.color("base0C").hex(),
        base0D = palette.color("base0D").hex(),
        base0E = palette.color("base0E").hex(),
    )
}

fn render_ghostty_theme(palette: &Palette) -> String {
    let terminal = palette.terminal_palette();
    let base00 = palette.color("base00");
    let base03 = palette.color("base03");
    let base05 = palette.color("base05");
    let base07 = palette.color("base07");

    format!(
        concat!(
            "background = {background}\n",
            "foreground = {foreground}\n",
            "cursor-color = {cursor}\n",
            "selection-background = {selection_bg}\n",
            "selection-foreground = {selection_fg}\n",
            "palette = 0={ansi0}\n",
            "palette = 1={ansi1}\n",
            "palette = 2={ansi2}\n",
            "palette = 3={ansi3}\n",
            "palette = 4={ansi4}\n",
            "palette = 5={ansi5}\n",
            "palette = 6={ansi6}\n",
            "palette = 7={ansi7}\n",
            "palette = 8={bright0}\n",
            "palette = 9={bright1}\n",
            "palette = 10={bright2}\n",
            "palette = 11={bright3}\n",
            "palette = 12={bright4}\n",
            "palette = 13={bright5}\n",
            "palette = 14={bright6}\n",
            "palette = 15={bright7}\n"
        ),
        background = base00.hex(),
        foreground = base05.hex(),
        cursor = base07.hex(),
        selection_bg = base03.hex(),
        selection_fg = base05.hex(),
        ansi0 = terminal.normal[0].hex(),
        ansi1 = terminal.normal[1].hex(),
        ansi2 = terminal.normal[2].hex(),
        ansi3 = terminal.normal[3].hex(),
        ansi4 = terminal.normal[4].hex(),
        ansi5 = terminal.normal[5].hex(),
        ansi6 = terminal.normal[6].hex(),
        ansi7 = terminal.normal[7].hex(),
        bright0 = terminal.bright[0].hex(),
        bright1 = terminal.bright[1].hex(),
        bright2 = terminal.bright[2].hex(),
        bright3 = terminal.bright[3].hex(),
        bright4 = terminal.bright[4].hex(),
        bright5 = terminal.bright[5].hex(),
        bright6 = terminal.bright[6].hex(),
        bright7 = terminal.bright[7].hex(),
    )
}

fn render_qtct_config(path: &Path, style: &str, general_font: &str, fixed_font: &str) -> String {
    format!(
        "[Appearance]\ncustom_palette=true\nstandard_dialogs=default\nstyle={style}\ncolor_scheme_path={}\n\n[Fonts]\nfixed=\"{fixed_font}\"\ngeneral=\"{general_font}\"\n",
        path.display(),
    )
}

struct QtFonts {
    general: String,
    fixed: String,
}

fn extract_qt_fonts(content: &str) -> QtFonts {
    QtFonts {
        general: extract_ini_value(content, "Fonts", "general")
            .unwrap_or_else(|| "Sans Serif,12".into()),
        fixed: extract_ini_value(content, "Fonts", "fixed")
            .unwrap_or_else(|| "Monospace,12".into()),
    }
}

fn preferred_qt_style(content: &str) -> String {
    match extract_ini_value(content, "Appearance", "style") {
        Some(style) if !style.eq_ignore_ascii_case("kvantum") => style,
        _ => "Fusion".into(),
    }
}

fn extract_ini_value(content: &str, section: &str, key: &str) -> Option<String> {
    let mut current_section = None::<String>;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            current_section = Some(trimmed.trim_matches(['[', ']']).to_owned());
            continue;
        }

        if current_section.as_deref()? != section {
            continue;
        }

        let (current_key, value) = trimmed.split_once('=')?;
        if current_key.trim().eq_ignore_ascii_case(key) {
            return Some(value.trim().trim_matches('"').to_owned());
        }
    }

    None
}

fn write_text(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create `{}`", parent.display()))?;
    }

    let existing = fs::read_to_string(path).unwrap_or_default();
    if existing == content {
        return Ok(());
    }

    match fs::write(path, content) {
        Ok(()) => Ok(()),
        Err(error)
            if error.kind() == std::io::ErrorKind::PermissionDenied
                || error.raw_os_error() == Some(30) =>
        {
            fs::remove_file(path)
                .with_context(|| format!("failed to replace read-only `{}`", path.display()))?;
            fs::write(path, content)
                .with_context(|| format!("failed to write `{}`", path.display()))
        }
        Err(error) => Err(error).with_context(|| format!("failed to write `{}`", path.display())),
    }
}

fn clear_override_css(path: &Path) -> Result<()> {
    write_text(
        path,
        "/* Managed by walbridge. GTK runtime colors now come from generated themes, not per-user gtk.css overrides. */\n",
    )
}

fn render_gtk_theme(
    template: &str,
    base_css_path: &str,
    values: &std::collections::BTreeMap<String, String>,
) -> String {
    let mut rendered = format!("@import url(\"file://{base_css_path}\");\n\n");
    rendered.push_str(&render_template(template, values));
    rendered
}

fn current_gtk_theme() -> Result<String> {
    let output = Command::new("gsettings")
        .args(["get", "org.gnome.desktop.interface", "gtk-theme"])
        .output()
        .context("failed to run `gsettings get org.gnome.desktop.interface gtk-theme`")?;
    anyhow::ensure!(
        output.status.success(),
        "`gsettings get org.gnome.desktop.interface gtk-theme` failed: {}",
        String::from_utf8_lossy(&output.stderr).trim()
    );

    Ok(String::from_utf8_lossy(&output.stdout)
        .trim()
        .trim_matches('\'')
        .to_string())
}

fn set_gtk_theme(theme_name: &str) -> Result<()> {
    let output = Command::new("gsettings")
        .args([
            "set",
            "org.gnome.desktop.interface",
            "gtk-theme",
            theme_name,
        ])
        .output()
        .with_context(|| format!("failed to run `gsettings set ... {theme_name}`"))?;
    anyhow::ensure!(
        output.status.success(),
        "`gsettings set org.gnome.desktop.interface gtk-theme {theme_name}` failed: {}",
        String::from_utf8_lossy(&output.stderr).trim()
    );
    Ok(())
}
